---
title: "iteraetions and list columns"
author: "nz2333"
date: "11/19/2021"
output: github_document
---

```{r}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Lists

```{r}
l = list(
          vec_numeric = 5:8,
          vec_logical = c(TRUE, TRUE, FALSE, TRUE, FALSE, FALSE),
          mat = matrix(1:8, nrow = 2, ncol = 4),
          summary = summary(rnorm(100))
          )
```

## `for` loop
create a new list
```{r}
list_norm = 
  list(
    a = rnorm(20, mean = 3, sd = 1), 
    b = rnorm(20, mean = 0, sd = 5),
    c = rnorm(20, mean = 10, sd = 0.2), 
    d = rnorm(20, mean = -3, sd = 1)
  )
```

```{r}
list_norm[1]
```

pause and get the old function. 
```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Input mst be numeric")
  }
  
  if(length(x) < 3) {
    stop("Input at least three numbers")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(
    mean = mean_x, 
    sd = sd_x
  )

}
```

I can apply this function to each list element. 

```{r}
mean_and_sd(list_norm[[1]])
mean_and_sd(list_norm[[2]])
mean_and_sd(list_norm[[3]])
mean_and_sd(list_norm[[4]])
```

Let's use a for loop:
```{r}
output = vector("list", length = 4)

for (i in 1:4) {
  
output[[i]] = mean_and_sd(list_norm[[i]])
}
```




